//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int id { get; set; }
        public string url { get; set; }
        public string title { get; set; }
        public string sub_title { get; set; }
        public string descr { get; set; }
        public string keyword { get; set; }
        public string auth_image { get; set; }
        public string image { get; set; }
        public string text { get; set; }
        public string author { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> likes { get; set; }
        public string s1 { get; set; }
        public string s2 { get; set; }
        public string s3 { get; set; }
        public int POS { get; set; }
        public bool STATUS { get; set; }
    }
}
