//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodDonorDetail
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string patient_name { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string doctor_name { get; set; }
        public string hospital_name { get; set; }
        public string when_required { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public string ReqTo { get; set; }
        public string ReqStatus { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
    }
}
