//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calorie
    {
        public int id { get; set; }
        public string Food_Group { get; set; }
        public string Food_Name { get; set; }
        public Nullable<double> Protein__g_ { get; set; }
        public Nullable<double> Fat__g_ { get; set; }
        public Nullable<double> Carbohydrates__g_ { get; set; }
        public Nullable<double> Ash__g_ { get; set; }
        public Nullable<double> Calories { get; set; }
        public string Starch__g_ { get; set; }
        public string Sucrose__g_ { get; set; }
        public string Glucose__g_ { get; set; }
        public string Fructose__g_ { get; set; }
        public string Lactose__g_ { get; set; }
        public string Maltose__g_ { get; set; }
        public Nullable<double> Alcohol__g_ { get; set; }
        public Nullable<double> Water__g_ { get; set; }
        public Nullable<double> Caffeine__mg_ { get; set; }
        public Nullable<double> Theobromine__mg_ { get; set; }
        public Nullable<double> Sugar__g_ { get; set; }
        public string Galactose__g_ { get; set; }
        public Nullable<double> Fiber__g_ { get; set; }
        public Nullable<double> Calcium__mg_ { get; set; }
        public Nullable<double> Iron__mg_ { get; set; }
        public Nullable<double> Magnesium__mg_ { get; set; }
        public Nullable<double> Phosphorus__mg_ { get; set; }
        public Nullable<double> Potasssium__mg_ { get; set; }
        public Nullable<double> Sodium__mg_ { get; set; }
        public Nullable<double> Zinc__mg_ { get; set; }
        public Nullable<double> Cupper__mg_ { get; set; }
        public string Fluoride__mcg_ { get; set; }
        public Nullable<double> Manganese__mg_ { get; set; }
        public Nullable<double> Selenium__mcg_ { get; set; }
        public Nullable<double> Vitamin_A__IU_ { get; set; }
        public Nullable<double> Retinol__mcg_ { get; set; }
        public Nullable<double> Retinol_Equivalents__mcg_ { get; set; }
        public Nullable<double> Beta_Carotene__mcg_ { get; set; }
        public Nullable<double> Alpha_Carotene__mcg_ { get; set; }
        public Nullable<double> Vitamin_E__mg_ { get; set; }
        public Nullable<double> Vitamin_D__mcg_ { get; set; }
        public string Vitamin_D2__Ergocalciferol____mcg_ { get; set; }
        public Nullable<double> Vitamin_D3__Cholecalciferol___mcg_ { get; set; }
        public Nullable<double> Beta_Cryptoxanthin__mcg_ { get; set; }
        public Nullable<double> Lycopene__mcg_ { get; set; }
        public Nullable<double> Lutein_and_Zeaxanthin__mcg_ { get; set; }
        public Nullable<double> Vitamin_C__mg_ { get; set; }
        public Nullable<double> Thiamin__B1___mg_ { get; set; }
        public Nullable<double> Riboflavin__B2___mg_ { get; set; }
        public Nullable<double> Niacin__B3___mg_ { get; set; }
        public Nullable<double> Vitamin_B5__mg_ { get; set; }
        public Nullable<double> Vitamin_B6__mg_ { get; set; }
        public Nullable<double> Folate__B9___mg_ { get; set; }
        public Nullable<double> Vitamin_B12 { get; set; }
        public Nullable<double> Choline__mg_ { get; set; }
        public Nullable<double> Cholesterol__mg_ { get; set; }
        public Nullable<double> Saturated_Fat__g_ { get; set; }
        public Nullable<double> Net_Carbs { get; set; }
    }
}
