//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrer
    {
        public int id { get; set; }
        public string c_title { get; set; }
        public string descrp { get; set; }
        public string Keywords { get; set; }
        public string link { get; set; }
        public string Text { get; set; }
        public Nullable<bool> sidebar { get; set; }
        public Nullable<bool> sidebanner { get; set; }
        public Nullable<bool> cat_gallery { get; set; }
        public string gal_id { get; set; }
        public int POS { get; set; }
        public bool STATUS { get; set; }
    }
}
