//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_employee_master
    {
        public int id { get; set; }
        public Nullable<int> docId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public string EmpName { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> pharmacyId { get; set; }
        public string gcmkey { get; set; }
    
        public virtual ClinicDetail ClinicDetail { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
