//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorMaster
    {
        public int id { get; set; }
        public int docId { get; set; }
        public string name { get; set; }
        public string mci_no { get; set; }
        public string AboutUs { get; set; }
        public string online_appointment { get; set; }
        public string dept_id { get; set; }
        public string experience { get; set; }
        public string Fee { get; set; }
        public string HospitalAffiliation { get; set; }
        public string Membership { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Isclaimed { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
