//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_server
    {
        public int id { get; set; }
        public string mailserver { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string port { get; set; }
        public string ssl { get; set; }
        public string sendto { get; set; }
        public int POS { get; set; }
        public bool STATUS { get; set; }
    }
}
