//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class make_appointment
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public Nullable<int> clinic_id { get; set; }
        public string show_history { get; set; }
        public string remarks { get; set; }
        public string AppointmentStatus { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<long> QueueNo { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> PatientAge { get; set; }
        public string PatientSex { get; set; }
        public Nullable<int> CurrentQueueNo { get; set; }
        public Nullable<int> scheduleId { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ClinicDetail ClinicDetail { get; set; }
        public virtual clinicSchedule clinicSchedule { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
