//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PharmacyMaster()
        {
            this.PharmacyPrescriptions = new HashSet<PharmacyPrescription>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string pharmacy_name { get; set; }
        public string dl_no { get; set; }
        public string file_upload { get; set; }
        public string image { get; set; }
        public string PharmacyAddress { get; set; }
        public string PharmacyPhnNo { get; set; }
        public string contact_person_name { get; set; }
        public string lat_log { get; set; }
        public string Announcement { get; set; }
        public string PharmacyCategory { get; set; }
        public string SellOnline { get; set; }
        public string PharmacyType { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<int> DeliveryDistance { get; set; }
        public string PharmacyImageUpload { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyPrescription> PharmacyPrescriptions { get; set; }
    }
}
