//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacyPrescription
    {
        public int id { get; set; }
        public Nullable<int> prescriptionId { get; set; }
        public Nullable<int> PharmacyId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string QuotationDescription { get; set; }
        public Nullable<bool> isBestQuote { get; set; }
        public string DrugAvailability { get; set; }
        public Nullable<bool> IsFilterQuoteDone { get; set; }
        public string PrescriptionStatus { get; set; }
        public string PrescriptionEditDescription { get; set; }
        public Nullable<decimal> NewRate { get; set; }
    
        public virtual PharmacyMaster PharmacyMaster { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
