//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedzoidSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string User_Address { get; set; }
        public string latlong { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
